# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0029_communitytypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitytypes', to='Community.CommunityTypes'),
        ),
    ]
