# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-12 13:32
from __future__ import unicode_literals

import Community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0031_communitytypes_typeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image_thumbnail',
            field=models.ImageField(null=True, upload_to=Community.models.get_file_path),
        ),
    ]
