# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0032_community_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='forum',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
