# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-02 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0031_communitytypes_typeno'),
        ('Category', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorytype', to='Community.CommunityTypes'),
        ),
    ]
